stages:
  - build
  - test

image: $CI_REGISTRY/maierhofer/environment-model:v0.2.1

before_script:
  - conda create -n commonroad python=3.6
  - source activate commonroad
  - bash ./ci/install_cps_software.sh


build-library:
  stage: build
  script:
    - cmake -DCRCCOSY_LIBRARY_DIR="$HOME"/commonroad-curvilinear-coordinate-system -DCMAKE_BUILD_TYPE=Release .
    - make env_model -j4

build-standalone:
  stage: build
  script:
    - cmake -DCRCCOSY_LIBRARY_DIR="$HOME"/commonroad-curvilinear-coordinate-system -DCMAKE_BUILD_TYPE=Release .
    - make env_model_example_node -j4

build-test:
  stage: build
  script:
    - cmake -DCRCCOSY_LIBRARY_DIR="$HOME"/commonroad-curvilinear-coordinate-system -DCMAKE_BUILD_TYPE=Debug .
    - make env_model_test -j4
  artifacts:
    paths:
      - ./tests/env_model_test
      - ./tests/testScenarios/*
    expire_in: 20 minutes

test:
  stage: test
  script:
    - ./tests/env_model_test --gtest_output="xml:report.xml"
  dependencies:
    - build-test
  artifacts:
    reports:
      junit: ./tests/report.xml
