stages:
  - build
  - test

image: maierhofer/environment-model

before_script:
  - conda create -n commonroad python=3.8
  - source activate commonroad
  - bash ./ci/install_cps_software.sh


build-standalone:
  stage: build
  script:
    - cmake -DCRCCOSY_LIBRARY_DIR="$HOME"/commonroad-curvilinear-coordinate-system -DCMAKE_BUILD_TYPE=Release .
    - make env_model_lib -j4

build-test:
  stage: build
  script:
    - cmake -DCRCCOSY_LIBRARY_DIR="$HOME"/commonroad-curvilinear-coordinate-system -DCMAKE_BUILD_TYPE=Debug .
    - make env_model_test -j4
  artifacts:
    paths:
      - env_model_test
    expire_in: 20 minutes

test:
  stage: test
  script:
    - ./env_model_test --gtest_output="xml:report.xml"
  dependencies:
    - build-test
  artifacts:
    reports:
      junit: report.xml
