repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:

      - id: ruff
        args: [ --fix ]
      - id: ruff-format
        exclude: 'tests/scenarios/.*'

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        exclude: 'third_party/.*'
