# PEP 621 metadata
[project]
# name = "crcpp"
name = "commonroad_cpp"
version = "2022.0.0"
readme = "README.md"
requires-python = ">=3.7,<3.11"
# license = "License :: OSI Approved :: GNU Affero General Public License v3"
license = {file = "LICENSE"}
authors = [
  {email = "sebastian.maierhofer@tum.de"},
  {name = "Sebastian Maierhofer"}
]
description = "CommonRoad C++ Environment Model"

dependencies = [
  # "commonroad-io>=2021.4",
]

[project.optional-dependencies]
test = [
   "numpy>=1.20.0",
   "pytest>=5.3.2"
]
docs = [
   "sphinx~=5.2.3",
   "sphinx-pyproject~=0.1.0"
]

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "scikit-build~=0.15.0",
    "cmake~=3.24.0",
    "ninja",
    "pybind11~=2.10.0",
    ]

build-backend = "setuptools.build_meta"

[tool.sphinx-pyproject]
language = "en"

[tool.cibuildwheel]
# build = "cp*"
skip = "cp36-* pp* *-musllinux*"

archs = ["auto"]
# archs = ["x86_64"]

# Increase pip debugging output
#build-verbosity = 1

#before-test = "pip install -r {project}/test_requirements.txt"

[tool.cibuildwheel.linux]
#manylinux-x86_64-image = "manylinux2014"
manylinux-x86_64-image = "manylinux_2_24"

