# PEP 621 metadata
[project]
name = "commonroad_cpp"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.7,<3.12"
license = {file = "LICENSE"}
authors = [
  {email = "sebastian.maierhofer@tum.de"},
  {name = "Sebastian Maierhofer"}
]
description = "CommonRoad C++ Environment Model"

dependencies = [ ]

[project.optional-dependencies]
test = [
   "commonroad-io>=2021.4",
   "numpy>=1.20.0",
   "pytest>=5.3.2"
]
docs = [
   "sphinx~=5.2.3",
   "sphinx-pyproject~=0.1.0"
]

[build-system]
# NOTE: Update README.md if you change "requires" here
requires = [
    "setuptools>=61.0",
    "wheel",
    "scikit-build~=0.15.0",
    "cmake~=3.24.0",
    "ninja",
    "pybind11~=2.10.0",
     "setuptools_scm[toml]>=6.2"
    ]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.sphinx-pyproject]
language = "en"

[tool.cibuildwheel]
# build = "cp*"
skip = "pp*"

archs = ["auto"]
# archs = ["x86_64"]

# Disable pip warning about newer versions being available - they're just noise in CI
environment = { PIP_DISABLE_PIP_VERSION_CHECK="1" }

# Increase pip debugging output
#build-verbosity = 1

# Skip tests on musllinux due to missing wheels
test-skip = "*i686 *-musllinux*"

test-extras = ["test"]

test-command = "python -m pytest {package}/tests/python"
