// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phantom_obstacle.proto

#ifndef PROTOBUF_INCLUDED_phantom_5fobstacle_2eproto
#define PROTOBUF_INCLUDED_phantom_5fobstacle_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "obstacle.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_phantom_5fobstacle_2eproto 

namespace protobuf_phantom_5fobstacle_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_phantom_5fobstacle_2eproto
namespace commonroad {
class PhantomObstacle;
class PhantomObstacleDefaultTypeInternal;
extern PhantomObstacleDefaultTypeInternal _PhantomObstacle_default_instance_;
}  // namespace commonroad
namespace google {
namespace protobuf {
template<> ::commonroad::PhantomObstacle* Arena::CreateMaybeMessage<::commonroad::PhantomObstacle>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace commonroad {

// ===================================================================

class PhantomObstacle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:commonroad.PhantomObstacle) */ {
 public:
  PhantomObstacle();
  virtual ~PhantomObstacle();

  PhantomObstacle(const PhantomObstacle& from);

  inline PhantomObstacle& operator=(const PhantomObstacle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PhantomObstacle(PhantomObstacle&& from) noexcept
    : PhantomObstacle() {
    *this = ::std::move(from);
  }

  inline PhantomObstacle& operator=(PhantomObstacle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PhantomObstacle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PhantomObstacle* internal_default_instance() {
    return reinterpret_cast<const PhantomObstacle*>(
               &_PhantomObstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PhantomObstacle* other);
  friend void swap(PhantomObstacle& a, PhantomObstacle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PhantomObstacle* New() const final {
    return CreateMaybeMessage<PhantomObstacle>(NULL);
  }

  PhantomObstacle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PhantomObstacle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PhantomObstacle& from);
  void MergeFrom(const PhantomObstacle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PhantomObstacle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .commonroad.SetBasedPrediction prediction = 2;
  bool has_prediction() const;
  void clear_prediction();
  static const int kPredictionFieldNumber = 2;
  private:
  const ::commonroad::SetBasedPrediction& _internal_prediction() const;
  public:
  const ::commonroad::SetBasedPrediction& prediction() const;
  ::commonroad::SetBasedPrediction* release_prediction();
  ::commonroad::SetBasedPrediction* mutable_prediction();
  void set_allocated_prediction(::commonroad::SetBasedPrediction* prediction);

  // required uint32 obstacle_id = 1;
  bool has_obstacle_id() const;
  void clear_obstacle_id();
  static const int kObstacleIdFieldNumber = 1;
  ::google::protobuf::uint32 obstacle_id() const;
  void set_obstacle_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:commonroad.PhantomObstacle)
 private:
  void set_has_obstacle_id();
  void clear_has_obstacle_id();
  void set_has_prediction();
  void clear_has_prediction();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::commonroad::SetBasedPrediction* prediction_;
  ::google::protobuf::uint32 obstacle_id_;
  friend struct ::protobuf_phantom_5fobstacle_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PhantomObstacle

// required uint32 obstacle_id = 1;
inline bool PhantomObstacle::has_obstacle_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PhantomObstacle::set_has_obstacle_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PhantomObstacle::clear_has_obstacle_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PhantomObstacle::clear_obstacle_id() {
  obstacle_id_ = 0u;
  clear_has_obstacle_id();
}
inline ::google::protobuf::uint32 PhantomObstacle::obstacle_id() const {
  // @@protoc_insertion_point(field_get:commonroad.PhantomObstacle.obstacle_id)
  return obstacle_id_;
}
inline void PhantomObstacle::set_obstacle_id(::google::protobuf::uint32 value) {
  set_has_obstacle_id();
  obstacle_id_ = value;
  // @@protoc_insertion_point(field_set:commonroad.PhantomObstacle.obstacle_id)
}

// optional .commonroad.SetBasedPrediction prediction = 2;
inline bool PhantomObstacle::has_prediction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PhantomObstacle::set_has_prediction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PhantomObstacle::clear_has_prediction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::commonroad::SetBasedPrediction& PhantomObstacle::_internal_prediction() const {
  return *prediction_;
}
inline const ::commonroad::SetBasedPrediction& PhantomObstacle::prediction() const {
  const ::commonroad::SetBasedPrediction* p = prediction_;
  // @@protoc_insertion_point(field_get:commonroad.PhantomObstacle.prediction)
  return p != NULL ? *p : *reinterpret_cast<const ::commonroad::SetBasedPrediction*>(
      &::commonroad::_SetBasedPrediction_default_instance_);
}
inline ::commonroad::SetBasedPrediction* PhantomObstacle::release_prediction() {
  // @@protoc_insertion_point(field_release:commonroad.PhantomObstacle.prediction)
  clear_has_prediction();
  ::commonroad::SetBasedPrediction* temp = prediction_;
  prediction_ = NULL;
  return temp;
}
inline ::commonroad::SetBasedPrediction* PhantomObstacle::mutable_prediction() {
  set_has_prediction();
  if (prediction_ == NULL) {
    auto* p = CreateMaybeMessage<::commonroad::SetBasedPrediction>(GetArenaNoVirtual());
    prediction_ = p;
  }
  // @@protoc_insertion_point(field_mutable:commonroad.PhantomObstacle.prediction)
  return prediction_;
}
inline void PhantomObstacle::set_allocated_prediction(::commonroad::SetBasedPrediction* prediction) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(prediction_);
  }
  if (prediction) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      prediction = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, prediction, submessage_arena);
    }
    set_has_prediction();
  } else {
    clear_has_prediction();
  }
  prediction_ = prediction;
  // @@protoc_insertion_point(field_set_allocated:commonroad.PhantomObstacle.prediction)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace commonroad

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_phantom_5fobstacle_2eproto
