stages:
  - compile
  - test
  - python
  - coverage
  - static-test
  - docs
  - publish

image: $CI_REGISTRY/cps/rapid-prototyping-setup/ci-lite:1.0

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"

### static test ###
clang-format:
  image: $CI_REGISTRY/cps/rapid-prototyping-setup/ci:1.4
  stage: static-test
  script: ./ci/clang-format.sh
  needs: []

clang-tidy:
  image: $CI_REGISTRY/cps/rapid-prototyping-setup/ci:1.4
  stage: static-test
  script: ./ci/clang-tidy.sh
  needs:
    - job: build-compile-commands
      artifacts: true

cppcheck:
  stage: static-test
  script:
    cppcheck
    --project=build/compile_commands.json
    -i"$(pwd)/external"
  needs:
    - job: build-compile-commands
      artifacts: true

### build project ###
build-compile-commands:
  stage: compile
  script:
    # run CMake in order to get compile_commands.json
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/commonroad/dist -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  ..
    - cd ..
  needs: []
  artifacts:
    paths:
      - ./build/compile_commands.json
    expire_in: 20 minutes

build-clang:
  stage: compile
  variables:
    CC: clang
    CXX: clang++
  script:
    - cmake -G "Ninja Multi-Config" -S . -B build
    - cmake --build build --config Release --target env_model
  needs: []

build-gcc:
  stage: compile
  variables:
    CC: gcc
    CXX: g++
  script:
    - cmake -G "Ninja Multi-Config" -S . -B build
    - cmake --build build --config Release --target env_model
  needs: []

build-standalone:
  stage: compile
  script:
    - cmake -G "Ninja Multi-Config" -S . -B build
    - cmake --build build --config Release --target env_model_example_node
  needs: []

build-test:
  stage: compile
  script:
    - cmake -G "Ninja Multi-Config" -S . -B build
    - cmake --build build --config Debug --target env_model_test
  needs: []
  artifacts:
    paths:
      - ./build/
      - ./dist/
    expire_in: 30 minutes

build-run-coverage:
  stage: compile
  script:
    - cmake -G "Ninja Multi-Config" -S . -B build -DENV_MODEL_BUILD_CODE_COVERAGE=ON
    - cmake --build build --config Debug --target env_model_test
    - cmake --build build --config Debug --target env_model_coverage
  needs: []
  artifacts:
    paths:
      - ./build/
      - ./dist/
    expire_in: 30 minutes

build-sdist:
  stage: python
  tags:
    - wheel
  image: $CI_REGISTRY/cps/rapid-prototyping-setup/wheelenv:1.0
  script:
    - python3 --version
    - pipx run build --sdist
  needs: []
  artifacts:
    paths:
      - dist/*.tar.gz
    expire_in: 30 minutes

build-wheel:
  stage: python
  tags:
    - wheel
  image: $CI_REGISTRY/cps/rapid-prototyping-setup/wheelenv:1.0
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:20.10-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    CIBW_BEFORE_ALL: "git config --global url.\"https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/\".insteadOf \"git@gitlab.lrz.de:\""
    CIBW_BUILD_VERBOSITY: 0
    CIBW_BUILD: '*'
  script:
    - pipx run build --sdist
    - cibuildwheel --platform linux dist/*.tar.gz
  needs:
    - job: build-sdist
      artifacts: true
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 30 minutes

upload-wheel:
  stage: python
  image: $CI_REGISTRY/cps/rapid-prototyping-setup/wheelenv:1.0
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - twine upload dist/*.tar.gz wheelhouse/*.whl
  needs:
    - job: build-sdist
      artifacts: true
    - job: build-wheel
      artifacts: true

### tests ###
test:
  stage: test
  script:
    - cmake --build build --config Debug --target test
  needs:
    - job: build-test
      artifacts: true
  artifacts:
    # Upload reports even if tests fail
    when: always
    reports:
      junit: build/test-reports/*.xml

#build-test-python-37:
#  stage: test
#  before_script:
#    - source activate cr37
#    - *python-prepare
#  script:
#    - python setup.py install
#    - python -m pytest tests/python
#  needs: []
#
#build-test-python-38:
#  stage: test
#  before_script:
#    - source activate cr38
#    - *python-prepare
#  script:
#    - python setup.py install
#    - python -m pytest tests/python
#  needs: []
#
#build-test-python-39:
#  stage: test
#  before_script:
#    - source activate cr39
#    - *python-prepare
#  script:
#    - python setup.py install
#    - python -m pytest tests/python
#  needs: []

### coverage ###
coverage-analyze:
  stage: coverage
  script:
    - gcovr --version
    - gcovr
      -f src/
      -e src/commonroad_cpp/interfaces/standalone/main.cpp
      -e src/commonroad_cpp/interfaces/commonroad/protobufFormat
      -e src/commonroad_cpp/geometry/shape.h
      -e src/commonroad_cpp/interfaces/pybind/
      -e /commonroad/dist/include/yaml-cpp/
      --print-summary
      --exclude-unreachable-branches
      --output coverage.xml
      --xml
  needs:
    - job: build-run-coverage
      artifacts: true
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
          coverage_format: cobertura
          path: coverage.xml

coverage-report:
  stage: coverage
  script:
    - gcovr --version
    - gcovr
      -f src/
      -e src/commonroad_cpp/interfaces/standalone/main.cpp
      -e src/commonroad_cpp/interfaces/commonroad/protobufFormat
      -e src/commonroad_cpp/geometry/shape.h
      -e src/commonroad_cpp/interfaces/pybind/
      -e /commonroad/dist/include/yaml-cpp/
      --print-summary
      --exclude-unreachable-branches
      --output coverage.html
      --html
      --html-details
    - mkdir coverage
    - mv coverage*.html coverage
  needs:
    - job: build-run-coverage
      artifacts: true
  artifacts:
    paths:
      - coverage
    expose_as: 'Coverage Report'
    expire_in: 30 minutes

### create documentation ###
docs:
  stage: docs
  script:
    - mkdir -p build && cd build
    - cmake -DCMAKE_PREFIX_PATH=/commonroad/dist -DCMAKE_BUILD_TYPE=Debug -DENV_MODEL_BUILD_DOXYGEN=ON  ..
    - make doc_doxygen ..
  dependencies: []
  artifacts:
    paths:
      - build/doc_doxygen/html/
    expose_as: 'Doxygen Documentation'
    expire_in: 30 minutes

pages:
  stage: publish
  script:
    - mv build/doc_doxygen/html public
  needs:
    - job: docs
      artifacts: true
  artifacts:
    paths:
      - public
    expire_in: 20 minutes
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
