//
// Created by Sebastian Maierhofer.
// Technical University of Munich - Cyber-Physical Systems Group
// Copyright (c) 2021 Sebastian Maierhofer - Technical University of Munich. All rights reserved.
// Credits: BMW Car@TUM
//

#include "memory"
#include "vector"
#include <iostream>
#include <map>
#include <unordered_map>

#include "types_and_definitions.h"
#include "traffic_signs.h"

// automatically generated from commonroad-io with:
// sed -r 's/([A-Z_0-9]+) = '\''([^'\'']+)'\''/ {TrafficSignTypes::\1, "\2"}, /'

TrafficSignTable TrafficSignIDGermany = {
    {TrafficSignTypes::WARNING_DANGER_SPOT, "101"},
    {TrafficSignTypes::WARNING_RIGHT_BEFORE_LEFT, "102"},
    {TrafficSignTypes::WARNING_LEFT_CURVE, "103-10"},
    {TrafficSignTypes::WARNING_RIGHT_CURVE, "103-20"},
    {TrafficSignTypes::WARNING_STEEP_HILL_DOWNWARDS, "108"},
    {TrafficSignTypes::WARNING_SLIPPERY_ROAD, "114"},
    {TrafficSignTypes::WARNING_CONSTRUCTION_SITE, "123"},
    {TrafficSignTypes::WARNING_TRAFFIC_QUEUES_LIKELY, "124"},
    {TrafficSignTypes::WARNING_ONCOMING_TRAFFIC, "125"},
    {TrafficSignTypes::WARNING_TRAFFIC_LIGHTS_AHEAD, "131"},
    {TrafficSignTypes::WARNING_PEDESTRIANS_RIGHT, "133-10"},
    {TrafficSignTypes::WARNING_PEDESTRIANS_LEFT, "133-20"},
    {TrafficSignTypes::WARNING_CROSSING_CYCLIST, "138"},
    {TrafficSignTypes::WARNING_ANIMAL_CROSSING_RIGHT, "142-10"},
    {TrafficSignTypes::WARNING_LOOSE_GRAVEL, "145-50"},
    {TrafficSignTypes::RAILWAY, "201"},
    {TrafficSignTypes::YIELD, "205"},
    {TrafficSignTypes::STOP, "206"},
    {TrafficSignTypes::PRIORITY_OPPOSITE_DIRECTION, "208"},
    {TrafficSignTypes::TURN_RIGHT_AHEAD, "209-10"},
    {TrafficSignTypes::TURN_LEFT_AHEAD, "209-20"},
    {TrafficSignTypes::KEEP_STRAIGHT_AHEAD, "209-30"},
    {TrafficSignTypes::PRESCRIBED_DIRECTION_RIGHT, "211-20"},
    {TrafficSignTypes::ROUNDABOUT, "215"},
    {TrafficSignTypes::ONEWAY_RIGHT, "220-10"},
    {TrafficSignTypes::ONEWAY_LEFT, "220-20"},
    {TrafficSignTypes::PRESCRIBED_PASSING_LEFT, "222-10"},
    {TrafficSignTypes::PRESCRIBED_PASSING_RIGHT, "222-20"},
    {TrafficSignTypes::DO_NOT_DRIVE_ON_SHOULDER_LANE, "223.2"},
    {TrafficSignTypes::DO_NOT_DRIVE_ON_SHOULDER_LANE_2_LANE, "223.2-50"},
    {TrafficSignTypes::DO_NOT_DRIVE_ON_SHOULDER_LANE_3_LANE, "223.2-51"},
    {TrafficSignTypes::BUS_STOP, "224-50"},
    {TrafficSignTypes::BIKEWAY, "237"},
    {TrafficSignTypes::SIDEWALK, "239"},
    {TrafficSignTypes::PEDESTRIAN_AND_BICYCLE_ROAD, "240"},
    {TrafficSignTypes::PEDESTRIAN_ZONE_START, "242.1"},
    {TrafficSignTypes::PEDESTRIAN_ZONE_END, "242.2"},
    {TrafficSignTypes::BICYCLE_ROAD_START, "244.1"},
    {TrafficSignTypes::BICYCLE_ROAD_END, "244.2"},
    {TrafficSignTypes::BUSLANE, "245"},
    {TrafficSignTypes::BAN_ALL_VEHICLES, "250"},
    {TrafficSignTypes::BAN_CARS, "251"},
    {TrafficSignTypes::BAN_TRUCKS, "253"},
    {TrafficSignTypes::BAN_BICYCLE, "254"},
    {TrafficSignTypes::BAN_MOTORCYCLE, "255"},
    {TrafficSignTypes::BAN_BUS, "257-54"},
    {TrafficSignTypes::BAN_PEDESTRIAN, "259"},
    {TrafficSignTypes::BAN_CAR_TRUCK_BUS_MOTORCYCLE, "260"},
    {TrafficSignTypes::BAN_VEHICLES_CARRYING_DANGEROUS_GOODS, "261"},
    {TrafficSignTypes::MAX_WEIGHT, "262"},
    {TrafficSignTypes::MAX_WIDTH, "264"},
    {TrafficSignTypes::MAX_HEIGHT, "265"},
    {TrafficSignTypes::MAX_LENGTH, "266"},
    {TrafficSignTypes::NO_ENTRY, "267"},
    {TrafficSignTypes::ENVIRONMENTAL_ZONE_START, "270.1"},
    {TrafficSignTypes::ENVIRONMENTAL_ZONE_END, "270.2"},
    {TrafficSignTypes::U_TURN, "272"},
    {TrafficSignTypes::MAX_SPEED, "274"},
    {TrafficSignTypes::MAX_SPEED_ZONE_START, "274.1"},
    {TrafficSignTypes::MAX_SPEED_ZONE_END, "274.2"},
    {TrafficSignTypes::MIN_SPEED, "275"},
    {TrafficSignTypes::NO_OVERTAKING_START, "276"},
    {TrafficSignTypes::NO_OVERTAKING_TRUCKS_START, "277"},
    {TrafficSignTypes::MAX_SPEED_END, "278"},
    {TrafficSignTypes::NO_OVERTAKING_END, "280"},
    {TrafficSignTypes::NO_OVERTAKING_TRUCKS_END, "281"},
    {TrafficSignTypes::ALL_MAX_SPEED_AND_OVERTAKING_END, "282"},
    {TrafficSignTypes::NO_STOP_START_RIGHT, "283-10"},
    {TrafficSignTypes::NO_STOP_CENTER_RIGHT, "283-30"},
    {TrafficSignTypes::RESTRICTED_STOP_CENTER_RIGHT, "286-30"},
    {TrafficSignTypes::RIGHT_OF_WAY, "301"},
    {TrafficSignTypes::PRIORITY, "306"},
    {TrafficSignTypes::PRIORITY_OVER_ONCOMING, "308"},
    {TrafficSignTypes::TOWN_SIGN, "310"},
    {TrafficSignTypes::TOWN_SIGN_BACK, "311"},
    {TrafficSignTypes::PARKING_AREA, "314"},
    {TrafficSignTypes::PARKING_AREA_LEFT, "314-10"},
    {TrafficSignTypes::PARKING_AREA_RIGHT, "314-20"},
    {TrafficSignTypes::PARKING_AREA_RIGHT_LEFT, "314-30"},
    {TrafficSignTypes::TRAFFIC_CALMED_AREA_START, "325.1"},
    {TrafficSignTypes::TRAFFIC_CALMED_AREA_END, "325.2"},
    {TrafficSignTypes::TUNNEL, "327"},
    {TrafficSignTypes::EMERYGECNY_STOP, "328"},
    {TrafficSignTypes::INTERSTATE_START, "330.1"},
    {TrafficSignTypes::INTERSTATE_END, "330.2"},
    {TrafficSignTypes::HIGHWAY_START, "331.1"},
    {TrafficSignTypes::HIGHWAY_END, "331.2"},
    {TrafficSignTypes::HIGHWAY_EXIT_WITH_PLACE_NAME, "332"},
    {TrafficSignTypes::EXIT_ROUTE, "332.1"},
    {TrafficSignTypes::HIGHWAY_EXIT, "333"},
    {TrafficSignTypes::EXIT_BUILT_UP, "333-21"},
    {TrafficSignTypes::EXIT_GENERAL, "333-22"},
    {TrafficSignTypes::PEDESTRIANS_CROSSING, "350"},
    {TrafficSignTypes::WATER_PROTECTION_ZONE, "354"},
    {TrafficSignTypes::TRAFFIC_ASSISTANTS, "356"},
    {TrafficSignTypes::DEAD_END, "357"},
    {TrafficSignTypes::POLICE, "363"},
    {TrafficSignTypes::EMERGENCY_CALL_STATION, "365-51"},
    {TrafficSignTypes::GAS_STATION, "365-52"},
    {TrafficSignTypes::CAMP_AND_CARAVAN_SITE, "365-60"},
    {TrafficSignTypes::ATTRACTION_POINT, "386.1"},
    {TrafficSignTypes::TOURISTIC_ROUTE, "386.2"},
    {TrafficSignTypes::NEARBY_ATTRACTION_POINT, "386.3"},
    {TrafficSignTypes::HIGHWAY_INTERSECTION, "406-50"},
    {TrafficSignTypes::DIRECTION_ARROW_SIGN_MULTI, "418-20"},
    {TrafficSignTypes::DIRECTION_ARROW_SIGN_SINGLE, "419-20"},
    {TrafficSignTypes::DIRECTION_SIGN_CONSOLIDATED, "434-50"},
    {TrafficSignTypes::EXPRESSWAY_ARROW_DIRECTION, "430-20"},
    {TrafficSignTypes::ARROW_SIGN_POST_POINT_OF_INTEREST_LEFT, "432-10"},
    {TrafficSignTypes::STATION, "432-20"},
    {TrafficSignTypes::GUIDE_SIGN_TABLE, "434"},
    {TrafficSignTypes::ADVANCE_DIRECTION, "438"},
    {TrafficSignTypes::DIRECTIONS_SIGN, "439"},
    {TrafficSignTypes::EXPRESSWAY_ENTRANCE_DIRECTIONS, "440"},
    {TrafficSignTypes::INTERSTATE_ANNOUNCEMENT, "448"},
    {TrafficSignTypes::INTERSTATE_ADVANCE_DIRECTION, "449"},
    {TrafficSignTypes::HIGHWAY_EXIT_AHEAD_100_METER, "450-50"},
    {TrafficSignTypes::HIGHWAY_EXIT_AHEAD_200_METER, "450-51"},
    {TrafficSignTypes::HIGHWAY_EXIT_AHEAD_300_METER, "450-52"},
    {TrafficSignTypes::EXPRESSWAY_EXIT_100_METRES, "450-53"},
    {TrafficSignTypes::EXPRESSWAY_EXIT_200_METRES, "450-54"},
    {TrafficSignTypes::EXPRESSWAY_EXIT_300_METRES, "450-55"},
    {TrafficSignTypes::INTERSTATE_DISTANCE, "453"},
    {TrafficSignTypes::DETOUR_SKETCH, "458"},
    {TrafficSignTypes::DETOUR_STRAIGHT, "455.1-30"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_LEFT, "460-10"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_GET_IN_LEFT_LANE, "460-12"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_ANNOUNCEMENT_RIGHT, "460-20"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_RIGHT, "460-21"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_GET_IN_RIGHT_LANE, "460-22"},
    {TrafficSignTypes::DETOUR_ON_DEMAND_STRAIGHTFORWARD, "460-30"},
    {TrafficSignTypes::TRANSITION_3_LEFT_2_TRANSITIONED, "501-15"},
    {TrafficSignTypes::TRANSITION_1_LEFT_1_STRAIGHT, "501-16"},
    {TrafficSignTypes::LANE_BOARD_NO_OPPOSITE_TWO_LANES, "521-30"},
    {TrafficSignTypes::THREE_LANES_NO_ONCOMING_LANES, "521-31"},
    {TrafficSignTypes::FOUR_LANES_NO_ONCOMING_LANES, "521-32"},
    {TrafficSignTypes::FIVE_LANES_NO_ONCOMING_LANES, "521-33"},
    {TrafficSignTypes::LANE_BOARD_3_LANES_NO_OPPOSITE_WITH_SIGNS, "525"},
    {TrafficSignTypes::NARROWING_LANES_1_LANE_FROM_RIGHT, "531-10"},
    {TrafficSignTypes::NARROWING_LANES_1_LANE_FROM_LEFT, "531-20"},
    {TrafficSignTypes::NARROWING_LANES_2_LANES_PLUS_1_LEFT, "531-21"},
    {TrafficSignTypes::FOUR_LANES_NO_ONCOMING_TRAFFIC_TWO_RIGHT_LANES_TURN_RIGHT, "533-22"},
    {TrafficSignTypes::MERGING_LANES_1_LANE_PLUS_1_LANE_RIGHT, "550-20"},
    {TrafficSignTypes::BARRIER, "600-35"},
    {TrafficSignTypes::BARRIER_GATE_100_800, "600-30"},
    {TrafficSignTypes::BARRIER_GATE_100_1200, "600-31"},
    {TrafficSignTypes::BARRIER_GATE_100_1600, "600-32"},
    {TrafficSignTypes::BARRIER_GATE_250_1600, "600-34"},
    {TrafficSignTypes::BARRIER_GATE, "600-38"},
    {TrafficSignTypes::ROAD_WARNING_POST_SCRAPER_BEACON_RIGHT, "605-10"},
    {TrafficSignTypes::ROAD_WARNING_POST_SCRAPER_BEACON_LEFT, "605-20"},
    {TrafficSignTypes::ROAD_WARNING_POST_ARROW_BEACON_RIGHT, "605-11"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_SINGLE, "625-10"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_SMALL, "625-11"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_MEDIUM, "625-12"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_LARGE, "625-13"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_SINGLE, "625-20"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_SMALL, "625-21"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_MEDIUM, "625-22"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_LARGE, "625-23"},
    {TrafficSignTypes::WARNING_PANEL_RIGHT, "626-10"},
    {TrafficSignTypes::WARNING_PANEL_LEFT, "626-20"},
    {TrafficSignTypes::WARNING_PANEL_STRAIGHT_BROAD, "626-30"},
    {TrafficSignTypes::WARNING_PANEL_STRAIGHT_HIGH, "626-31"},
    {TrafficSignTypes::GUIDE_SILL_WITH_GUIDE_BEACON_RIGHT, "628-10"},
    {TrafficSignTypes::GUIDE_RAIL_WITH_GUIDE_BEACON_RIGHT, "629-10"},
    {TrafficSignTypes::GUIDE_PANEL_WITH_GUIDE_BEACON_RIGHT, "629-20"},
    {TrafficSignTypes::GREEN_ARROW, "720"},
    {TrafficSignTypes::ADDITION_LEFT_DIRECTION, "1000"},
    {TrafficSignTypes::ADDITION_LEFT_DIRECTION_1, "1000-10"},
    {TrafficSignTypes::ADDITION_LEFT_DIRECTION_DANGER_POINT, "1000-11"},
    {TrafficSignTypes::ADDITION_RIGHT_DIRECTION_1, "1000-20"},
    {TrafficSignTypes::ADDITION_RIGHT_DIRECTION_DANGER_POINT, "1000-21"},
    {TrafficSignTypes::ADDITION_BOTH_DIRECTIONS_HORIZONTAL, "1000-30"},
    {TrafficSignTypes::ADDITION_BOTH_DIRECTIONS_VERTICAL, "1000-31"},
    {TrafficSignTypes::ADDITION_VALID_FOR_X_METERS, "1001-30"},
    {TrafficSignTypes::ADDITION_VALID_FOR_X_KILOMETERS, "1001-31"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_OPPOSITE_RIGHT_YIELD, "1002-10"},
    {TrafficSignTypes::ADDITION_LEFT_TRAFFIC_PRIORITY_WITH_STRAIGHT_RIGHT_YIELD, "1002-11"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_OPPOSITE_YIELD, "1002-12"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_RIGHT_YIELD, "1002-13"},
    {TrafficSignTypes::ADDITION_LEFT_TRAFFIC_PRIORITY_WITH_STRAIGHT_YIELD, "1002-14"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_OPPOSITE_LEFT_YIELD, "1002-20"},
    {TrafficSignTypes::ADDITION_RIGHT_TRAFFIC_PRIORITY_WITH_STRAIGHT_LEFT_YIELD, "1002-21"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_OPPOSITE_YIELD, "1002-22"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_LEFT_YIELD, "1002-23"},
    {TrafficSignTypes::ADDITION_RIGHT_TRAFFIC_PRIORITY_WITH_STRAIGHT_YIELD, "1002-24"},
    {TrafficSignTypes::ADDITION_VALID_IN_X_METERS, "1004-30"},
    {TrafficSignTypes::ADDITION_VALID_IN_X_KILOMETERS, "1004-31"},
    {TrafficSignTypes::ADDITION_VALID_IN_400_METRES, "1004-33"},
    {TrafficSignTypes::ADDITION_VALID_IN_600_METRES, "1004-34"},
    {TrafficSignTypes::ADDITION_VALID_IN_2_KILOMETERS, "1004-35"},
    {TrafficSignTypes::ADDITION_OIL_ON_ROAD, "1006-30"},
    {TrafficSignTypes::ADDITION_SMOKE, "1006-31"},
    {TrafficSignTypes::ADDITION_LOOSE_GRAVEL, "1006-32"},
    {TrafficSignTypes::ADDITION_BUILDING_SITE_EXIT, "1006-33"},
    {TrafficSignTypes::ADDITION_DAMAGED_ROAD, "1006-34"},
    {TrafficSignTypes::ADDITION_DIRTY_ROAD, "1006-35"},
    {TrafficSignTypes::ADDITION_DANGER_OF_COLLISION, "1006-36"},
    {TrafficSignTypes::ADDITION_TOAD_MIGRATION, "1006-37"},
    {TrafficSignTypes::ADDITION_DANGER_OF_CONGESTION, "1006-38"},
    {TrafficSignTypes::ADDITION_RESTRICTED_VIEW_DUE_TO_TREES, "1006-39"},
    {TrafficSignTypes::DANGER_INDICATION_SMOKE, "1007-31"},
    {TrafficSignTypes::ADDITION_CHILDREN_PLAYING_ON_ROAD, "1010-10"},
    {TrafficSignTypes::ADDITION_WINTER_SPORTS_ALLOWED, "1010-11"},
    {TrafficSignTypes::ADDITION_TRAILERS_ALLOWED_TO_PARK_MORE_THAN_14_DAYS, "1010-12"},
    {TrafficSignTypes::ADDITION_CARAVANS_ALLOWED_TO_PARK_MORE_THAN_14_DAYS, "1010-13"},
    {TrafficSignTypes::ADDITION_ROLLING_HIGHWAY, "1010-14"},
    {TrafficSignTypes::ADDITION_LOADING_AREA, "1012-30"},
    {TrafficSignTypes::ADDITION_END, "1012-31"},
    {TrafficSignTypes::ADDITION_GET_OFF_BICYCLES, "1012-32"},
    {TrafficSignTypes::ADDITION_NO_MOPEDS, "1012-33"},
    {TrafficSignTypes::ADDITION_GREEN_WAVE_AT_KM_H, "1012-34"},
    {TrafficSignTypes::ADDITION_STOP_HERE_AT_RED, "1012-35"},
    {TrafficSignTypes::ADDITION_NOISE_CONTROL, "1012-36"},
    {TrafficSignTypes::ADDITION_INFLOW_REGULATION, "1012-37"},
    {TrafficSignTypes::ADDITION_SECONDARY_LANE, "1012-38"},
    {TrafficSignTypes::ADDITION_SCHOOL, "1012-50"},
    {TrafficSignTypes::ADDITION_KINDERGARTEN, "1012-51"},
    {TrafficSignTypes::ADDITION_RETIREMENT_HOME, "1012-52"},
    {TrafficSignTypes::ADDITION_HOSPITAL, "1012-53"},
    {TrafficSignTypes::ADDITION_RESIDENTS_PERMITTED, "1020-30"},
    {TrafficSignTypes::ADDITION_BICYCLES_PERMITTED, "1022-10"},
    {TrafficSignTypes::ADDITION_CARS_PERMITTED, "1024-10"},
    {TrafficSignTypes::ADDITION_AGRICULTURE_PERMITTED, "1026-36"},
    {TrafficSignTypes::ADDITION_FOREST_PERMITTED, "1026-37"},
    {TrafficSignTypes::ADDITION_AGRICULTURE_FOREST_PERMITTED, "1026-38"},
    {TrafficSignTypes::ADDITION_GREEN_STICKER_PERMITTED, "1031-52"},
    {TrafficSignTypes::ADDITION_TIME_PERIOD_PERMITTED, "1040-30"},
    {TrafficSignTypes::ADDITION_MOTOR_VEHICLES_ALLOWED_MASS_3_5_TONS, "1048-12"},
    {TrafficSignTypes::ADDITION_MIN_MASS_3_5_TONS, "1049-13"},
    {TrafficSignTypes::ADDITION_NO_WATER_POLLUTANTS_LOADED, "1052-31"},
    {TrafficSignTypes::ALLOWED_MASS_7_5_TONS, "1053-33"},
    {TrafficSignTypes::ADDITION_VALID_ON_SHOULDER, "1053-34"},
    {TrafficSignTypes::ADDITION_VALID_WHEN_WET, "1053-35"}};

TrafficSignTable TrafficSignIDZamunda = {
    {TrafficSignTypes::WARNING_DANGER_SPOT, "101"},
    {TrafficSignTypes::WARNING_RIGHT_BEFORE_LEFT, "102"},
    {TrafficSignTypes::WARNING_STEEP_HILL_DOWNWARDS, "108"},
    {TrafficSignTypes::WARNING_SLIPPERY_ROAD, "114"},
    {TrafficSignTypes::WARNING_CONSTRUCTION_SITE, "123"},
    {TrafficSignTypes::WARNING_CROSSING_CYCLIST, "138"},
    {TrafficSignTypes::WARNING_ANIMAL_CROSSING_RIGHT, "142-10"},
    {TrafficSignTypes::RAILWAY, "201"},
    {TrafficSignTypes::YIELD, "205"},
    {TrafficSignTypes::STOP, "206"},
    {TrafficSignTypes::PRIORITY_OPPOSITE_DIRECTION, "208"},
    {TrafficSignTypes::TURN_RIGHT_AHEAD, "209-10"},
    {TrafficSignTypes::TURN_LEFT_AHEAD, "209-20"},
    {TrafficSignTypes::ROUNDABOUT, "215"},
    {TrafficSignTypes::ONEWAY_RIGHT, "220-10"},
    {TrafficSignTypes::ONEWAY_LEFT, "220-20"},
    {TrafficSignTypes::PRESCRIBED_PASSING_LEFT, "222-10"},
    {TrafficSignTypes::PRESCRIBED_PASSING_RIGHT, "222-20"},
    {TrafficSignTypes::BIKEWAY, "237"},
    {TrafficSignTypes::SIDEWALK, "239"},
    {TrafficSignTypes::PEDESTRIAN_ZONE_START, "242.1"},
    {TrafficSignTypes::PEDESTRIAN_ZONE_END, "242.2"},
    {TrafficSignTypes::BICYCLE_ROAD_START, "244.1"},
    {TrafficSignTypes::BICYCLE_ROAD_END, "244.2"},
    {TrafficSignTypes::BUSLANE, "245"},
    {TrafficSignTypes::BAN_ALL_VEHICLES, "250"},
    {TrafficSignTypes::BAN_CARS, "251"},
    {TrafficSignTypes::BAN_TRUCKS, "253"},
    {TrafficSignTypes::BAN_BICYCLE, "254"},
    {TrafficSignTypes::BAN_MOTORCYCLE, "255"},
    {TrafficSignTypes::BAN_BUS, "257-54"},
    {TrafficSignTypes::BAN_PEDESTRIAN, "259"},
    {TrafficSignTypes::BAN_CAR_TRUCK_BUS_MOTORCYCLE, "260"},
    {TrafficSignTypes::BAN_VEHICLES_CARRYING_DANGEROUS_GOODS, "261"},
    {TrafficSignTypes::MAX_WEIGHT, "262"},
    {TrafficSignTypes::MAX_WIDTH, "264"},
    {TrafficSignTypes::MAX_HEIGHT, "265"},
    {TrafficSignTypes::MAX_LENGTH, "266"},
    {TrafficSignTypes::NO_ENTRY, "267"},
    {TrafficSignTypes::U_TURN, "272"},
    {TrafficSignTypes::MAX_SPEED, "274"},
    {TrafficSignTypes::MAX_SPEED_ZONE_START, "274.1"},
    {TrafficSignTypes::MAX_SPEED_ZONE_END, "274.2"},
    {TrafficSignTypes::MIN_SPEED, "275"},
    {TrafficSignTypes::NO_OVERTAKING_START, "276"},
    {TrafficSignTypes::NO_OVERTAKING_TRUCKS_START, "277"},
    {TrafficSignTypes::MAX_SPEED_END, "278"},
    {TrafficSignTypes::NO_OVERTAKING_TRUCKS_END, "281"},
    {TrafficSignTypes::ALL_MAX_SPEED_AND_OVERTAKING_END, "282"},
    {TrafficSignTypes::RIGHT_OF_WAY, "301"},
    {TrafficSignTypes::PRIORITY, "306"},
    {TrafficSignTypes::PRIORITY_OVER_ONCOMING, "308"},
    {TrafficSignTypes::TOWN_SIGN, "310"},
    {TrafficSignTypes::TRAFFIC_CALMED_AREA_START, "325.1"},
    {TrafficSignTypes::TRAFFIC_CALMED_AREA_END, "325.2"},
    {TrafficSignTypes::TUNNEL, "327"},
    {TrafficSignTypes::INTERSTATE_START, "330.1"},
    {TrafficSignTypes::INTERSTATE_END, "330.2"},
    {TrafficSignTypes::HIGHWAY_START, "331.1"},
    {TrafficSignTypes::HIGHWAY_END, "331.2"},
    {TrafficSignTypes::EXIT_BUILT_UP, "333-21"},
    {TrafficSignTypes::EXIT_GENERAL, "333-22"},
    {TrafficSignTypes::PEDESTRIANS_CROSSING, "350"},
    {TrafficSignTypes::DEAD_END, "357"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_SINGLE, "625-10"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_SMALL, "625-11"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_MEDIUM, "625-12"},
    {TrafficSignTypes::DIRECTION_SIGN_LEFT_LARGE, "625-13"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_SINGLE, "625-20"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_SMALL, "625-21"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_MEDIUM, "625-22"},
    {TrafficSignTypes::DIRECTION_SIGN_RIGHT_LARGE, "625-23"},
    {TrafficSignTypes::WARNING_PANEL_RIGHT, "626-10"},
    {TrafficSignTypes::WARNING_PANEL_LEFT, "626-20"},
    {TrafficSignTypes::WARNING_PANEL_STRAIGHT_BROAD, "626-30"},
    {TrafficSignTypes::WARNING_PANEL_STRAIGHT_HIGH, "626-31"},
    {TrafficSignTypes::GREEN_ARROW, "720"},
    {TrafficSignTypes::ADDITION_LEFT_DIRECTION_1, "1000-10"},
    {TrafficSignTypes::ADDITION_LEFT_DIRECTION_DANGER_POINT, "1000-11"},
    {TrafficSignTypes::ADDITION_RIGHT_DIRECTION_1, "1000-20"},
    {TrafficSignTypes::ADDITION_RIGHT_DIRECTION_DANGER_POINT, "1000-21"},
    {TrafficSignTypes::ADDITION_BOTH_DIRECTIONS_HORIZONTAL, "1000-30"},
    {TrafficSignTypes::ADDITION_BOTH_DIRECTIONS_VERTICAL, "1000-31"},
    {TrafficSignTypes::ADDITION_VALID_FOR_X_METERS, "1001-30"},
    {TrafficSignTypes::ADDITION_VALID_FOR_X_KILOMETERS, "1001-31"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_OPPOSITE_RIGHT_YIELD, "1002-10"},
    {TrafficSignTypes::ADDITION_LEFT_TRAFFIC_PRIORITY_WITH_STRAIGHT_RIGHT_YIELD, "1002-11"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_OPPOSITE_YIELD, "1002-12"},
    {TrafficSignTypes::ADDITION_LEFT_TURNING_PRIORITY_WITH_RIGHT_YIELD, "1002-13"},
    {TrafficSignTypes::ADDITION_LEFT_TRAFFIC_PRIORITY_WITH_STRAIGHT_YIELD, "1002-14"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_OPPOSITE_LEFT_YIELD, "1002-20"},
    {TrafficSignTypes::ADDITION_RIGHT_TRAFFIC_PRIORITY_WITH_STRAIGHT_LEFT_YIELD, "1002-21"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_OPPOSITE_YIELD, "1002-22"},
    {TrafficSignTypes::ADDITION_RIGHT_TURNING_PRIORITY_WITH_LEFT_YIELD, "1002-23"},
    {TrafficSignTypes::ADDITION_RIGHT_TRAFFIC_PRIORITY_WITH_STRAIGHT_YIELD, "1002-24"},
    {TrafficSignTypes::ADDITION_VALID_IN_X_METERS, "1004-30"},
    {TrafficSignTypes::ADDITION_VALID_IN_X_KILOMETERS, "1004-31"},
    {TrafficSignTypes::ADDITION_RESIDENTS_PERMITTED, "1020-30"},
    {TrafficSignTypes::ADDITION_BICYCLES_PERMITTED, "1022-10"},
    {TrafficSignTypes::ADDITION_CARS_PERMITTED, "1024-10"},
    {TrafficSignTypes::ADDITION_AGRICULTURE_PERMITTED, "1026-36"},
    {TrafficSignTypes::ADDITION_FOREST_PERMITTED, "1026-37"},
    {TrafficSignTypes::ADDITION_AGRICULTURE_FOREST_PERMITTED, "1026-38"},
    {TrafficSignTypes::ADDITION_TIME_PERIOD_PERMITTED, "1040-30"},
    {TrafficSignTypes::ALLOWED_MASS_7_5_TONS, "1053-33"}};

TrafficSignTable TrafficSignIDUSA = {
    {TrafficSignTypes::MAX_SPEED, "R2-1"},
    {TrafficSignTypes::U_TURN, "R3-4"},
    {TrafficSignTypes::ROAD_WORK_AHEAD, "CW20-1"},
    {TrafficSignTypes::NO_PARKING_ANY_TIME, "R7-1"},
    {TrafficSignTypes::NO_STANDING, "R7-4"},
    {TrafficSignTypes::TOW_AWAY_ZONE, "R7-201a"},
    {TrafficSignTypes::ONE_WAY_LEFT, "R6-1L"},
    {TrafficSignTypes::ONE_WAY_RIGHT, "R6-1R"},
    {TrafficSignTypes::DO_NOT_ENTER, "R5-1"},
    {TrafficSignTypes::NO_LEFT_TURN, "R3-2"},
    {TrafficSignTypes::RIGHT_TURN_ONLY, "R3-5R"},
    {TrafficSignTypes::TURN_ONLY_LANES, "R3-8b"},
    {TrafficSignTypes::NO_RIGHT_TURN, "R3-1"},
    {TrafficSignTypes::KEEP_RIGHT, "R4-7"},
    {TrafficSignTypes::SIGNAL_AHEAD, "W3-3"},
    {TrafficSignTypes::LOADING_ZONE, "R8-3gP"},
    {TrafficSignTypes::NO_PARKING, "R8-3"},
    {TrafficSignTypes::LEFT_TURN_ONLY, "R3-5L"},
    {TrafficSignTypes::NO_STRAIGHT_THROUGH, "R3-27"},
    {TrafficSignTypes::LEFT_REVERSE_TURN, "W1-3L"},
    {TrafficSignTypes::PEDESTRIAN_WARNING, "W11-2"},
    {TrafficSignTypes::DIAGONAL_DOWNWARD_LEFT_ARROW, "M6-2aL"},
    {TrafficSignTypes::RIGHT_LANE_ENDS, "W4-2R"},
    {TrafficSignTypes::RESERVED_HANDICAP_PARKING, "R7-8"},
    {TrafficSignTypes::NO_PARKING_BUS_STOP, "R7-107"},
    {TrafficSignTypes::ON_PAVEMENT, "R8-3C"},
    {TrafficSignTypes::DO_NOT_BLOCK_INTERSECTION, "R10-7"},
    {TrafficSignTypes::WARNING_ARROW_LEFT, "W1-6L"},
};

TrafficSignTable TrafficSignIDSpain = {
    {TrafficSignTypes::YIELD, "r1"},
    {TrafficSignTypes::STOP, "r2"},
    {TrafficSignTypes::BAN_ALL_VEHICLES, "r100"},
    {TrafficSignTypes::NO_ENTRY, "r101"},
    {TrafficSignTypes::BAN_TRUCKS, "r106"},
    {TrafficSignTypes::MAX_WEIGHT, "r107"},
    {TrafficSignTypes::MAX_HEIGHT, "r205"},
    {TrafficSignTypes::MAX_SPEED, "r301"},
    {TrafficSignTypes::NO_OVERTAKING_START, "r305"},
    {TrafficSignTypes::NO_STOPPING, "r307"},
    {TrafficSignTypes::NO_WAITING, "r308"},
    {TrafficSignTypes::PEDESTRIANS_CROSSING, "s13"},
};

const std::unordered_map<SupportedTrafficSignCountry, TrafficSignTable *>
    TrafficSignLookupTableByCountry = {
        {SupportedTrafficSignCountry::GERMANY, &TrafficSignIDGermany},
        {SupportedTrafficSignCountry::ZAMUNDA, &TrafficSignIDZamunda},
        {SupportedTrafficSignCountry::USA, &TrafficSignIDUSA},
        {SupportedTrafficSignCountry::SPAIN, &TrafficSignIDSpain},
};

const std::unordered_map<std::string, std::vector<int>> priorityTable{
    std::pair<std::string, std::vector<int>>("1002-10", {5, 4, 4}),
    std::pair<std::string, std::vector<int>>("1002-12", {5, 4, -1}),
    std::pair<std::string, std::vector<int>>("1002-13", {5, -1, 4}),
    std::pair<std::string, std::vector<int>>("1002-11", {2, 2, 2}),
    std::pair<std::string, std::vector<int>>("1002-22", {-1, 4, 5}),
    std::pair<std::string, std::vector<int>>("1002-23", {4, -1, 5}),
    std::pair<std::string, std::vector<int>>("1002-14", {2, 2, -1}),
    std::pair<std::string, std::vector<int>>("1002-20", {4, 4, 5}),
    std::pair<std::string, std::vector<int>>("1002-21", {2, 2, 2}),
    std::pair<std::string, std::vector<int>>("1002-24", {-1, 2, 2}),
    std::pair<std::string, std::vector<int>>("306", {4, 5, 4}),
    std::pair<std::string, std::vector<int>>("301", {4, 5, 4}),
    std::pair<std::string, std::vector<int>>("205", {2, 2, 2}),
    std::pair<std::string, std::vector<int>>("206", {1, 1, 1}),
    std::pair<std::string, std::vector<int>>("102", {3, 3, 3}),
    std::pair<std::string, std::vector<int>>("720", {-1, -1, 0}),
};
