name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["self-hosted", "ubuntu-22.04", "ubuntu-24.04", "windows-2022", "windows-2025", "macos-15", "macos-26"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          # Increase build verbosity
          CIBW_BUILD_VERBOSITY: 1

          # Apparently libomp is already installed on macos-12, so this is unnecessary
          # CIBW_BEFORE_ALL_MACOS: brew install libomp
          # Build protobuf ourselves due to absl
          CIBW_BEFORE_ALL_MACOS: >
            brew install boost eigen range-v3 yaml-cpp googletest

          CIBW_BEFORE_BUILD_MACOS: >
            brew fetch --force --bottle-tag=arm64_monterey libomp &&
            brew reinstall libomp

          CIBW_ENVIRONMENT_WINDOWS: >
            CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"

          CIBW_BEFORE_ALL_WINDOWS: >
            C:\vcpkg\bootstrap-vcpkg.bat &&
            C:\vcpkg\vcpkg integrate install &&
            C:\vcpkg\vcpkg install zlib

          # brew fetch --force --bottle-tag=arm64_monterey libomp &&
          # brew reinstall $(brew --cache --bottle-tag=arm64_monterey libomp)

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
